// Used Deriv wire fields and the explicitly requested execution-schema handoff checks.
// serde_json::Value is confined to schema metadata in this test.
const FIELDS: &[(&str, &str, &str, &str, bool)] = &[
    (
        "active_symbols_request",
        "/properties/active_symbols",
        "\"string\"",
        "[\"full\",\"brief\"]",
        true,
    ),
    (
        "active_symbols_request",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "active_symbols_response",
        "/properties/active_symbols",
        "\"array\"",
        "null",
        false,
    ),
    (
        "active_symbols_response",
        "/properties/active_symbols/items/properties/underlying_symbol",
        "\"string\"",
        "null",
        true,
    ),
    (
        "active_symbols_response",
        "/properties/active_symbols/items/properties/underlying_symbol_name",
        "\"string\"",
        "null",
        true,
    ),
    (
        "active_symbols_response",
        "/properties/active_symbols/items/properties/pip_size",
        "\"number\"",
        "null",
        true,
    ),
    (
        "active_symbols_response",
        "/properties/active_symbols/items/properties/exchange_is_open",
        "\"integer\"",
        "[0,1]",
        true,
    ),
    (
        "active_symbols_response",
        "/properties/active_symbols/items/properties/is_trading_suspended",
        "\"integer\"",
        "[0,1]",
        true,
    ),
    (
        "active_symbols_response",
        "/properties/msg_type",
        "\"string\"",
        "[\"active_symbols\"]",
        true,
    ),
    (
        "active_symbols_response",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "contracts_for_request",
        "/properties/contracts_for",
        "\"string\"",
        "null",
        true,
    ),
    (
        "contracts_for_request",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for",
        "\"object\"",
        "null",
        false,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for/properties/available",
        "\"array\"",
        "null",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for/properties/available/items/properties/contract_type",
        "\"string\"",
        "null",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for/properties/available/items/properties/contract_category",
        "\"string\"",
        "null",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for/properties/available/items/properties/barriers",
        "\"number\"",
        "null",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for/properties/available/items/properties/min_contract_duration",
        "\"string\"",
        "null",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for/properties/available/items/properties/expiry_type",
        "\"string\"",
        "null",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/contracts_for/properties/available/items/properties/underlying_symbol",
        "\"string\"",
        "null",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/msg_type",
        "\"string\"",
        "[\"contracts_for\"]",
        true,
    ),
    (
        "contracts_for_response",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "forget_request",
        "/properties/forget",
        "\"string\"",
        "null",
        true,
    ),
    (
        "forget_request",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "forget_response",
        "/properties/forget",
        "\"integer\"",
        "[0,1]",
        false,
    ),
    (
        "forget_response",
        "/properties/msg_type",
        "\"string\"",
        "[\"forget\"]",
        true,
    ),
    (
        "forget_response",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "balance_request",
        "/properties/balance",
        "\"integer\"",
        "[1]",
        true,
    ),
    (
        "balance_request",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "balance_response",
        "/properties/balance",
        "\"object\"",
        "null",
        false,
    ),
    (
        "balance_response",
        "/properties/balance/properties/balance",
        "\"number\"",
        "null",
        true,
    ),
    (
        "balance_response",
        "/properties/balance/properties/currency",
        "\"string\"",
        "null",
        true,
    ),
    (
        "balance_response",
        "/properties/balance/properties/loginid",
        "\"string\"",
        "null",
        true,
    ),
    (
        "balance_response",
        "/properties/msg_type",
        "\"string\"",
        "[\"balance\"]",
        true,
    ),
    (
        "balance_response",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "get_accounts_request",
        "/properties/headers",
        "\"object\"",
        "null",
        true,
    ),
    (
        "get_accounts_request",
        "/properties/headers/properties/Authorization",
        "\"string\"",
        "null",
        true,
    ),
    (
        "get_accounts_request",
        "/properties/headers/properties/Deriv-App-ID",
        "\"string\"",
        "null",
        true,
    ),
    (
        "get_accounts_response",
        "/properties/data",
        "\"array\"",
        "null",
        false,
    ),
    (
        "get_accounts_response",
        "/properties/data/items/properties/account_id",
        "\"string\"",
        "null",
        true,
    ),
    (
        "get_accounts_response",
        "/properties/data/items/properties/account_type",
        "\"string\"",
        "[\"demo\",\"real\"]",
        true,
    ),
    (
        "get_accounts_response",
        "/properties/data/items/properties/status",
        "\"string\"",
        "[\"active\",\"inactive\"]",
        true,
    ),
    (
        "get_accounts_response",
        "/properties/data/items/properties/currency",
        "\"string\"",
        "null",
        true,
    ),
    (
        "websocket_response",
        "/properties/data",
        "\"object\"",
        "null",
        true,
    ),
    (
        "websocket_response",
        "/properties/data/properties/url",
        "\"string\"",
        "null",
        true,
    ),
    (
        "websocket_request",
        "/properties/path",
        "\"object\"",
        "null",
        true,
    ),
    (
        "websocket_request",
        "/properties/path/properties/accountId",
        "\"string\"",
        "null",
        true,
    ),
    (
        "websocket_request",
        "/properties/headers",
        "\"object\"",
        "null",
        true,
    ),
    (
        "websocket_request",
        "/properties/headers/properties/Authorization",
        "\"string\"",
        "null",
        true,
    ),
    (
        "websocket_request",
        "/properties/headers/properties/Deriv-App-ID",
        "\"string\"",
        "null",
        true,
    ),
    ("ticks_request", "/properties/ticks", "null", "null", true),
    (
        "ticks_request",
        "/properties/subscribe",
        "\"integer\"",
        "[1]",
        false,
    ),
    (
        "ticks_request",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "ticks_response",
        "/properties/tick",
        "\"object\"",
        "null",
        false,
    ),
    (
        "ticks_response",
        "/properties/tick/properties/epoch",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "ticks_response",
        "/properties/tick/properties/quote",
        "\"number\"",
        "null",
        false,
    ),
    (
        "ticks_response",
        "/properties/tick/properties/symbol",
        "\"string\"",
        "null",
        false,
    ),
    (
        "ticks_response",
        "/properties/tick/properties/pip_size",
        "\"number\"",
        "null",
        true,
    ),
    (
        "ticks_response",
        "/properties/subscription",
        "\"object\"",
        "null",
        false,
    ),
    (
        "ticks_response",
        "/properties/subscription/properties/id",
        "\"string\"",
        "null",
        true,
    ),
    (
        "ticks_response",
        "/properties/msg_type",
        "\"string\"",
        "[\"tick\"]",
        true,
    ),
    (
        "ticks_response",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "ticks_history_request",
        "/properties/ticks_history",
        "\"string\"",
        "null",
        true,
    ),
    (
        "ticks_history_request",
        "/properties/style",
        "\"string\"",
        "[\"candles\",\"ticks\"]",
        false,
    ),
    (
        "ticks_history_request",
        "/properties/end",
        "\"string\"",
        "null",
        true,
    ),
    (
        "ticks_history_request",
        "/properties/count",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "ticks_history_request",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "ticks_history_response",
        "/properties/history",
        "\"object\"",
        "null",
        false,
    ),
    (
        "ticks_history_response",
        "/properties/history/properties/prices",
        "\"array\"",
        "null",
        false,
    ),
    (
        "ticks_history_response",
        "/properties/history/properties/prices/items",
        "\"number\"",
        "null",
        false,
    ),
    (
        "ticks_history_response",
        "/properties/history/properties/times",
        "\"array\"",
        "null",
        false,
    ),
    (
        "ticks_history_response",
        "/properties/history/properties/times/items",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "ticks_history_response",
        "/properties/pip_size",
        "\"number\"",
        "null",
        false,
    ),
    (
        "ticks_history_response",
        "/properties/msg_type",
        "\"string\"",
        "[\"history\",\"tick\",\"candles\",\"ohlc\"]",
        true,
    ),
    (
        "ticks_history_response",
        "/properties/req_id",
        "\"integer\"",
        "null",
        false,
    ),
    (
        "proposal_request",
        "/properties/contract_type",
        "\"string\"",
        "[\"HIGHER\",\"LOWER\",\"MULTUP\",\"MULTDOWN\",\"UPORDOWN\",\"EXPIRYRANGE\",\"ONETOUCH\",\"CALLE\",\"ASIAND\",\"EXPIRYRANGEE\",\"DIGITDIFF\",\"DIGITMATCH\",\"DIGITOVER\",\"PUTE\",\"DIGITUNDER\",\"NOTOUCH\",\"CALL\",\"RANGE\",\"DIGITODD\",\"PUT\",\"ASIANU\",\"EXPIRYMISSE\",\"EXPIRYMISS\",\"DIGITEVEN\",\"TICKHIGH\",\"TICKLOW\",\"RESETCALL\",\"RESETPUT\",\"RUNHIGH\",\"RUNLOW\",\"ACCU\",\"VANILLALONGCALL\",\"VANILLALONGPUT\",\"TURBOSLONG\",\"TURBOSSHORT\"]",
        true,
    ),
    (
        "proposal_open_contract_response",
        "/properties/proposal_open_contract",
        "\"object\"",
        "null",
        false,
    ),
    (
        "proposal_open_contract_response",
        "/properties/proposal_open_contract/properties/status",
        "[\"null\",\"string\"]",
        "[\"open\",\"sold\",\"won\",\"lost\",\"cancelled\",null]",
        false,
    ),
    (
        "proposal_open_contract_response",
        "/properties/proposal_open_contract/properties/entry_spot",
        "[\"null\",\"string\"]",
        "null",
        false,
    ),
    (
        "proposal_open_contract_response",
        "/properties/proposal_open_contract/properties/entry_spot_time",
        "[\"integer\",\"null\"]",
        "null",
        false,
    ),
    (
        "proposal_open_contract_response",
        "/properties/proposal_open_contract/properties/exit_spot",
        "[\"null\",\"string\"]",
        "null",
        false,
    ),
    (
        "proposal_open_contract_response",
        "/properties/proposal_open_contract/properties/exit_spot_time",
        "[\"integer\",\"null\"]",
        "null",
        false,
    ),
    (
        "buy_response",
        "/properties/buy",
        "\"object\"",
        "null",
        false,
    ),
    (
        "buy_response",
        "/properties/buy/properties/buy_price",
        "\"number\"",
        "null",
        true,
    ),
    (
        "buy_response",
        "/properties/buy/properties/purchase_time",
        "\"integer\"",
        "null",
        true,
    ),
    (
        "buy_response",
        "/properties/buy/properties/contract_id",
        "\"integer\"",
        "null",
        true,
    ),
    (
        "buy_response",
        "/properties/buy/properties/transaction_id",
        "\"integer\"",
        "null",
        true,
    ),
    (
        "buy_response",
        "/properties/buy/properties/payout",
        "\"number\"",
        "null",
        true,
    ),
    (
        "buy_response",
        "/properties/buy/properties/start_time",
        "\"integer\"",
        "null",
        true,
    ),
    (
        "transaction_response",
        "/properties/transaction",
        "\"object\"",
        "null",
        false,
    ),
    (
        "transaction_response",
        "/properties/transaction/properties/action",
        "\"string\"",
        "[\"buy\",\"sell\",\"deposit\",\"withdrawal\"]",
        false,
    ),
];

#[test]
fn pinned_used_fields_types_nullability_enums_and_required_members() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("schemas/deriv/production_v20260819_0");
    let names = [
        "active_symbols",
        "balance",
        "buy",
        "contracts_for",
        "forget",
        "get_accounts",
        "portfolio",
        "proposal",
        "proposal_open_contract",
        "statement",
        "ticks",
        "ticks_history",
        "transaction",
        "websocket",
        "ws_public",
        "ws_demo",
        "ws_real",
    ];
    let mut schemas = std::collections::BTreeMap::new();
    for name in names {
        for direction in ["request", "response"] {
            let name = format!("{name}_{direction}");
            let bytes = std::fs::read(root.join(format!("{name}.schema.json"))).unwrap();
            let value: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
            assert_eq!(value["type"], "object");
            schemas.insert(name, value);
        }
    }
    assert_eq!(schemas.len(), 34);
    for &(name, pointer, types, enums, required) in FIELDS {
        let schema = &schemas[name];
        let node = schema
            .pointer(pointer)
            .unwrap_or_else(|| panic!("missing {name}{pointer}"));
        assert_eq!(
            node["type"],
            serde_json::from_str::<serde_json::Value>(types).unwrap(),
            "{name}{pointer} type/nullability"
        );
        assert_eq!(
            node["enum"],
            serde_json::from_str::<serde_json::Value>(enums).unwrap(),
            "{name}{pointer} enum"
        );
        if !pointer.ends_with("/items") {
            let (parent, field) = pointer.rsplit_once("/properties/").unwrap();
            let parent = schema.pointer(parent).unwrap();
            let actual = parent["required"]
                .as_array()
                .is_some_and(|list| list.iter().any(|item| item == field));
            assert_eq!(actual, required, "{name}{pointer} required membership");
        }
    }
    let buy = &schemas["buy_response"]["properties"]["buy"]["required"];
    for name in [
        "buy_price",
        "purchase_time",
        "contract_id",
        "transaction_id",
        "payout",
        "start_time",
    ] {
        assert!(buy.as_array().unwrap().iter().any(|value| value == name));
    }
    let contract =
        &schemas["proposal_open_contract_response"]["properties"]["proposal_open_contract"];
    assert!(contract.get("required").is_none());
    for name in [
        "entry_spot",
        "entry_spot_time",
        "exit_spot",
        "exit_spot_time",
    ] {
        assert!(
            contract["properties"][name]["type"]
                .as_array()
                .unwrap()
                .iter()
                .any(|value| value == "null")
        );
    }
    assert!(
        schemas["ticks_history_request"]["properties"]["count"]
            .get("maximum")
            .is_none()
    );
}
